update

diff --git a/deploy/receiver b/deploy/receiver
--- a/deploy/receiver
+++ b/deploy/receiver
@@ -18,77 +18,6 @@ mydeploy --base "$BASE" create --repo "$REPO_PATH"
 
 rc=$?
 if [[ $rc != 0 ]] ; then
-    exit $rc
+  echo "python script failed - exiting."
+  exit $rc
 fi
-
-echo "DONE"
-exit 1
-
-RUN_OPTIONS="-P -d -e CONTAINER_NAME=$BASE"
-
-# Find out the old container ID.
-OLD_ID=$(docker ps | grep "$BASE:latest" | cut -d ' ' -f 1)
-
-IMAGE_ID=$(docker images | grep $BASE | awk '{ print $3 }')
-
-echo "Found old Docker OLD_ID:$OLD_ID IMAGE_ID:$IMAGE_ID"
-
-if [ -e "$DOCKERFILE" ]
-then
-  # Look for the exposed port.
-  INTERNAL_PORT=$(grep -i "^EXPOSE" $DOCKERFILE | cut -d ' ' -f 2)
-  # Build and get the ID.
-  docker build -t $BUILD_ORG_NAME/$BASE $REPO_PATH
-
-  if [ $? -ne 0 ]
-  then
-    echo "Failed build - exiting."
-    exit
-  fi
-  echo "build finished"
-  ID=$(docker run $RUN_OPTIONS $BUILD_ORG_NAME/$BASE)
-
-  # Get the $PORT from the container.
-  if [ -n "$INTERNAL_PORT" ]
-  then
-    PORT=$(docker port $ID $INTERNAL_PORT | sed 's/0.0.0.0://')
-  fi
-  
-  if [ -z "$PORT" ]
-  then
-    echo "#################################################"
-    echo "Something went wrong, trying again."
-    echo "Killing the container we just launched."
-    docker kill $ID > /dev/null
-    echo "Launching a new one"
-    ID=$(docker run $RUN_OPTIONS $BUILD_ORG_NAME/$BASE)
-    PORT=$(docker port $ID $INTERNAL_PORT | sed 's/0.0.0.0://')
-    if [ -z "$PORT" ]
-    then
-      echo "docker run $RUN_OPTIONS $BUILD_ORG_NAME/$BASE"
-    else
-      echo "docker run $RUN_OPTIONS $BUILD_ORG_NAME/$BASE"
-    fi
-    echo "#################################################"
-  else
-    echo "Everything looks good."
-  fi
-
-else
-  echo "There is no Dockerfile present. ($DOCKERFILE)"
-  exit 1
-fi
-
-# Kill the old container by ID.
-if [ -n "$OLD_ID" ]
-then
-  CONTAINERS=$(docker ps | grep "$IMAGE_ID" | cut -d ' ' -f 1)
-  for container in $CONTAINERS
-  do
-    ID="$container"
-    docker kill "$ID" > /dev/null
-  done
-else
-  echo "Not killing any containers."
-fi
-
